# Generated by Django 2.0 on 2017-12-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'ユーザ'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_choiced_user', to='questionnaire.StudyOffice', verbose_name='第一希望研究室'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gpa',
            field=models.FloatField(default=0, verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='student_number',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='学生ID'),
        ),
    ]
