# Generated by Django 2.0 on 2017-12-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171213_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='display_name',
            field=models.CharField(blank=True, help_text='集計ページで学生IDの代わりに表示されます。', max_length=16, null=True, verbose_name='表示名'),
        ),
    ]
