# Generated by Django 2.0 on 2017-12-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyoffice',
            options={'ordering': ['number'], 'verbose_name': '研究室'},
        ),
        migrations.AddField(
            model_name='studyoffice',
            name='number',
            field=models.IntegerField(default=0, verbose_name='番号'),
        ),
        migrations.AddField(
            model_name='studyoffice',
            name='supervisor',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='studyoffice',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
